matrix:
  allow_failures:
    - os: linux
  include:
    - script:
        - set -o pipefail && xcodebuild test -workspace Dip.xcworkspace -scheme Dip -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' ONLY_ACTIVE_ARCH=NO | xcpretty -c
        - set -o pipefail && xcodebuild test -workspace Dip.xcworkspace -scheme Dip -sdk macosx -destination 'platform=macOS,arch=x86_64' ONLY_ACTIVE_ARCH=NO | xcpretty -c
        # - pod spec lint --allow-warnings
        - carthage build --no-skip-current
        - swift package clean && swift build && swift test
      os: osx
      osx_image: xcode10.2
      language: objective-c
      before_install:
        - gem install cocoapods --version 1.8.4 --no-document
    - script:
        - set -o pipefail && xcodebuild test -workspace Dip.xcworkspace -scheme Dip -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=latest' ONLY_ACTIVE_ARCH=NO | xcpretty -c
        - set -o pipefail && xcodebuild test -workspace Dip.xcworkspace -scheme Dip -sdk macosx -destination 'platform=macOS,arch=x86_64' ONLY_ACTIVE_ARCH=NO | xcpretty -c
        # - pod spec lint --allow-warnings
        - carthage build --no-skip-current
        - swift package clean && swift build && swift test
      os: osx
      osx_image: xcode11.2
      language: objective-c
      before_install:
        - gem install cocoapods --version 1.8.4 --no-document
    - script:
        - swift package clean && swift build && swift test
      os: linux
      dist: trusty
      sudo: required
      language: generic
      before_install:
        - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
        - cd ..
        - export SWIFT_VERSION=swift-5.1-RELEASE
        - wget https://swift.org/builds/swift-5.1-release/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz
        - tar xzf $SWIFT_VERSION-ubuntu14.04.tar.gz
        - export PATH="${PWD}/${SWIFT_VERSION}-ubuntu14.04/usr/bin:${PATH}"
        - cd Dip
    - script:
        - swift package clean && swift build && swift test
      os: linux
      dist: trusty
      sudo: required
      language: generic
      before_install:
        - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
        - cd ..
        - export SWIFT_VERSION=swift-5.0-RELEASE
        - wget https://swift.org/builds/swift-5.0-release/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz
        - tar xzf $SWIFT_VERSION-ubuntu14.04.tar.gz
        - export PATH="${PWD}/${SWIFT_VERSION}-ubuntu14.04/usr/bin:${PATH}"
        - cd Dip

notifications:
  email: false
